# Use a local build dir
BUILDDIR=.build

# Define a bib source to automatically copy the reference database on changes
BIBSOURCE=$(HOME)/path/to/mendeley.bib

# Leave the pdf file in the temp directory and don't copy it to the source directory
COPYPDF=
